services:
  discord-bot:
    build: .
    image: python-discord-bot-template
    container_name: darkside-bot-prod
    env_file:
      - .env.prod
    volumes:
      - ./database:/bot/database
      - ./discord.log:/bot/discord.log
    # Ajoute ces lignes pour ignorer les conteneurs des autres projets
    labels:
      com.docker.compose.project: darkside-prod